### PR TITLE
Easier configuration and prettier notification

### PR DESCRIPTION
**Pull request by ebeigarts**
I think there is no reason to set `ENV` variables, and channels are now configured for each webhook.

### CODE REVIEW

**Comment by matto1990** [comment]
Looks great and much easier to setup! I have a few small comments though:

* Can you mention in the README where you get the service URLs from. How to set them up through the Incoming Webhook integration etc.
* The message that I see in my Slack instance mentions localhost. Is this a configuration problem or a bug in the changes? If it's a configuration problem it would be good to add instructions to the README on how to set this up correctly. My Dokku instance is an old one that's been upgraded constantly so it might not be in the same state as a new installation now

image

**Comment by ebeigarts** [comment]
The message for me looks with a proper hostname screen shot 2015-03-20 at 13 05 43

I will add instructions about Slack integration.

**Comment by matto1990** [comment]
I figured that's what it would be. Is the fix to just change the name in `/etc/hostname`?

**Comment by ebeigarts** [comment]
Yes, I think so it uses `hostname -f`.

**Comment by ebeigarts** [comment]
Maybe it is better to use `/home/dokku/HOSTNAME` or `/home/dokku/VHOST`

**Comment by matto1990** [comment]
Yes I think it makes sense to use `VHOST` if it exists because the installation will set that up for you when you first install Dokku. Maybe if that file doesn't exist fall back to `hostname -f`?

**Comment by ebeigarts** [comment]
I think it is better to just use `hostname -f`. I think HOSTNAME/VHOST is used to create domains for apps - <appname>.example.com.

* `hostname -f` - dokku.example.com
* `HOSTNAME` - example.com
- `VHOST` - example.com

I like that it shows `dokku.example.com` and this was the way this plugin worked previously.

**Comment by matto1990** [comment]
Ok that sounds fine.

One other bug I've found is that you're using the contents of `/home/dokku/<app>/URL` to display the clickable URL. To make this work when vhosts are used I think you need to use `dokku url <app>`. On my instance the `URL` file shows `http://localhost:5000` whereas the dokku command returns the correct external URL.

**Comment by ebeigarts** [comment]
It is called WebHook URL in Slack (not Service URL), so I renamed it also here. Will check the URL.

**Comment by ebeigarts** [comment]
Changed the URL and tested, looks correct.

**Comment by matto1990** [comment]
Looks great! thanks so much for working on this! Merging now.

**Pull request merged**
