### PR TITLE
Use `$PLUGIN_PATH` instead of `$(dirname $0)/../`

### PR DESCRIPTION
**Pull request by Flink**
As discussed in https://github.com/progrium/dokku/pull/1425 and https://github.com/progrium/dokku/pull/1428

### CODE REVIEW

**Comment by matto1990** [comment]
Which version of Dokku is this avaliable from? Has it been released yet, or is this just a change in Dokku's master so far?

**Comment by Flink** [comment]
It has been available for a long time (since v0.2) so there’s no need to worry :)

**Comment by Flink** [comment]
But the change in plugins to use it instead of using `dirname` is quite new :wink:

**Comment by matto1990** [comment]
Got it! I saw your plugin management PR and assumed it was new with that. I'll make the change now!

**Comment by Flink** [comment]
The PR is what made the change since I was trying to use symlinks and `dirname` wouldn’t work as expected with them. The PR won’t use symlinks in fact but using `$PLUGIN_PATH` should give us more robust plugins :)

**Comment by Flink** [comment]
(and thanks!)

**Comment by matto1990** [comment]
No problem! Thanks you for the PR!

**Pull request merged**
